name: docs

on:
  create:
    tags:
      # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      - b[0-9][0-9][0-9]
      - publish-docs*
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # We install pywin32's latest release just to avoid re-building
      # We could instead try to use a GitHub artifact
      - name: Install latest release
        run: pip install --user --upgrade pywin32

      - name: Set Python user site directory
        run: python -c "import os,site; open(os.environ['GITHUB_ENV'], 'a').write(f'USER_DIR={site.USER_SITE}\n')"

      - name: Decompile shipped help file
        run: hh -decompile site ${env:USER_DIR}\PyWin32.chm

      - name: Rename root HTML file
        run: mv site\PyWin32.HTML site\index.html

      - uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: site/

  publish:
    runs-on: ubuntu-latest
    needs:
      - generate

    # Only publish tags
    if: github.event_name == 'create' && github.event.ref_type == 'tag'

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: documentation

      - name: Unpack archive
        run: python -m zipfile -e site.zip .

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
          commit_message: ${{ github.event.head_commit.message }}
        # Write .nojekyll at the root, see:
        # https://help.github.com/en/github/working-with-github-pages/about-github-pages#static-site-generators
          enable_jekyll: false
        # Only deploy if there were changes
          allow_empty_commit: false
